### ISSUE TITLE
Obfuscation sometimes fails

### ISSUE THREAD

**Issue by violine1101** [urielsalis/mc-crash-lib#11]
Example:

https://bugs.mojang.com/browse/MC-228443

Not quite sure what's going on there.

**Comment by urielsalis** [comment]
Seems to be due to java 16. Removing app// from the log makes it deobfuscate correctly

**Comment by violine1101** [comment]
Is the front guaranteed to be `app//` or can it also be `anything//`?

**Comment by violine1101** [comment]
Also depending on how trivial to fix this is for the general case, it might make sense to instead fix this upstream with a PR to proguard

**Comment by urielsalis** [comment]
Fixed by adding new regex

**Comment by urielsalis** [comment]
(It can be anything)

**Comment by Marcono1234** [comment]
Are you planning to create issues for this (and lambdas) at https://github.com/Guardsquare/proguard so they are aware of the issue? (even though you have have fixed it here now)

**Comment by urielsalis** [comment]
Yep, but it seems like they dont maintain it
